# Emuwork's stack.yaml configuration
#
# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-20.11

packages:
  - '.'
  - src-emubase/
  - src-trs80/
  - src-z80/
# - src-edas/

flags: {}
extra-package-dbs: []
system-ghc: true

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
